<!-- newsspec_{%= newsspec_number %} -->

<!--#include virtual="/news/special/{%= year %}/newsspec_{%= newsspec_number %}/inc/main_html.inc" -->

<!-- Load JS here Main JS will take care of loading all the dependencies -->
<script><!--#include virtual="/news/special/{%= year %}/newsspec_{%= newsspec_number %}/inc/compiled/main_js.inc" --> </script>

<!-- /newsspec_{%= newsspec_number %} -->